CREATE TABLE IF NOT EXISTS Users (
  eid BIGINT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  pwdhash VARCHAR(255) NOT NULL,
  netassest BIGINT DEFAULT 0
);