name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x application/gradlew

    - name: Build debug APK
      run: |
        cd application
        ./gradlew assembleDebug  # Adjust if you need to build a release APK or other variant

    - name: Create Build directory
      run: mkdir -p build

    - name: Move APK to build folder
      run: mv application/app/build/outputs/apk/debug/app-debug.apk build/  # Adjust paths as necessary for your project

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: build/app-debug.apk
