name: Android CI

on:
  push:
    branches:
      - main  # Adjust with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permissions for gradlew
      run: chmod +x ./application/gradlew

    - name: Build debug APK
      run: |
        cd application
        ./gradlew assembleDebug

    - name: Move APK to build folder
      run: |
        mkdir -p build
        mv application/app/build/outputs/apk/debug/app-debug.apk build/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: build/app-debug.apk
